apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: my-nodedb-app
spec:
  # 2 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: nodedb-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nodedb-app
    spec:
      containers:
        - name: mongo-db
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
        - name: nodedb-app
          # Run this image
          image: bibekk477/node-mongo-db:06
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      volumes:
        - name: mongo-storage
          emptyDir: {}
